// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MaterialUi = require("material-ui");

var initialState = {
  expanded: true
};

function Root(Props) {
  var message = Props.message;
  React.useReducer((function (state, action) {
          if (action) {
            return {
                    expanded: false
                  };
          } else {
            return {
                    expanded: true
                  };
          }
        }), initialState);
  return React.createElement(MaterialUi.AppBar, {
              children: React.createElement(MaterialUi.Toolbar, {
                    children: null
                  }, React.createElement(MaterialUi.IconButton, {
                        color: "contrast",
                        ariaLabel: "Menu",
                        children: "face"
                      }), React.createElement(MaterialUi.Button, {
                        raised: true,
                        children: "Click"
                      }), message)
            });
}

var make = Root;

exports.initialState = initialState;
exports.make = make;
/* react Not a pure module */
