// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_option = require("bs-platform/lib/js/js_option.js");

var _map = {"red":"red","orange":"orange","yellow":"yellow","olive":"olive","green":"green","teal":"teal","blue":"blue","violet":"violet","purple":"purple","pink":"pink","brown":"brown","grey":"grey","black":"black","facebook":"facebook","googleplus":"google plus","instagram":"instagram","linkedin":"linkedin","twitter":"twitter","vk":"vk","youtube":"youtube"};

var _revMap = {"red":"red","orange":"orange","yellow":"yellow","olive":"olive","green":"green","teal":"teal","blue":"blue","violet":"violet","purple":"purple","pink":"pink","brown":"brown","grey":"grey","black":"black","facebook":"facebook","google plus":"googleplus","instagram":"instagram","linkedin":"linkedin","twitter":"twitter","vk":"vk","youtube":"youtube"};

function colorToJs(param) {
  return _map[param];
}

function colorFromJs(param) {
  return _revMap[param];
}

function makeJsOptionMap(f, b) {
  return Js_option.map(Curry.__1(f), b);
}

function fromColor(param) {
  return Js_option.map(colorToJs, param);
}

var IconButton = {};

var Button = {};

function toString(position) {
  if (position === undefined) {
    return ;
  }
  switch (position) {
    case /* Static */0 :
        return "static";
    case /* Fixed */1 :
        return "fixed";
    case /* Absolute */2 :
        return "absolute";
    
  }
}

var AppBar = {
  toString: toString
};

var Toolbar = {};

var Table = {};

var TableBody = {};

function paddingToString(padding) {
  if (padding === undefined) {
    return ;
  }
  switch (padding) {
    case /* Default */0 :
        return "default";
    case /* Checkbox */1 :
        return "checkbox";
    case /* Dense */2 :
        return "dense";
    case /* None */3 :
        return "none";
    
  }
}

var TableCell = {
  paddingToString: paddingToString
};

exports.colorToJs = colorToJs;
exports.colorFromJs = colorFromJs;
exports.makeJsOptionMap = makeJsOptionMap;
exports.fromColor = fromColor;
exports.IconButton = IconButton;
exports.Button = Button;
exports.AppBar = AppBar;
exports.Toolbar = Toolbar;
exports.Table = Table;
exports.TableBody = TableBody;
exports.TableCell = TableCell;
/* No side effect */
