// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var Root$ReactTemplate = require("./Root/Root.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Root$ReactTemplate.make, {
          message: "Hello!"
        }), "index");

/*  Not a pure module */
