// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MaterialUi = require("material-ui");

function Header(Props) {
  return React.createElement(MaterialUi.AppBar, {
              children: React.createElement("div", undefined, "huhu")
            });
}

var make = Header;

exports.make = make;
/* react Not a pure module */
