// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");

function recTypeToJs(param) {
  return {
          one: param.one,
          key: param.key
        };
}

function recTypeFromJs(param) {
  return {
          one: param.one,
          key: param.key
        };
}

function handleResponse(data) {
  console.log("handleResponse");
  console.log(data.one);
  console.log(data.key);
  
}

Axios.get("http://echo.jsontest.com/key/value/one/two").then(function (response) {
      return Promise.resolve(handleResponse(recTypeFromJs(response.data)));
    });

var jsObject = {
  one: "einss",
  key: "schluesselll"
};

var record = recTypeFromJs(jsObject);

console.log(record.one);

console.log(record.key);

exports.recTypeToJs = recTypeToJs;
exports.recTypeFromJs = recTypeFromJs;
exports.handleResponse = handleResponse;
exports.jsObject = jsObject;
exports.record = record;
/*  Not a pure module */
