// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var p3 = "reached basement on junkLevel3";

var p2 = "further down the stairs to junkLevel2";

var p1 = "1 stage down on junkLevel1";

var p0 = "just on junkLevel0";

console.log("\npayload p0: " + p0 + "\npayload p1: " + p1 + "\npayload p2: " + p2 + "\npayload p3: " + p3 + "\n    ");

function someFunction(param) {
  console.log(param.name);
  
}

function otherFunction(thePerson) {
  console.log(thePerson.name);
  console.log(thePerson);
  
}

var person = {
  name: "Tina",
  age: 23
};

otherFunction(person);

someFunction(person);

function otherFunction$1(thePerson) {
  console.log(thePerson.name);
  console.log(thePerson.age);
  console.log(thePerson);
  
}

var person$1 = {
  name: "Tina",
  age: 23
};

otherFunction$1(person$1);

var junk = {
  payload: "just on junkLevel0",
  junkLevel1: {
    payload: "1 stage down on junkLevel1",
    junkLevel2: {
      payload: "further down the stairs to junkLevel2",
      junkLevel3: {
        payload: "reached basement on junkLevel3"
      }
    }
  }
};

exports.junk = junk;
exports.p0 = p0;
exports.p1 = p1;
exports.p2 = p2;
exports.p3 = p3;
exports.someFunction = someFunction;
exports.otherFunction = otherFunction$1;
exports.person = person$1;
/*  Not a pure module */
