// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


const jsObject = {
      myName: "blabla",
      myMethod: (greeting) => console.log(`${greeting}, Mr.${jsObject.myName}`)
    };
;

console.log(jsObject.myName);

jsObject.myName = "HERBERT";

jsObject.myMethod("Hello");

jsObject.myName = "Vanessa";

console.log(jsObject.myName);

jsObject.myMethod("huhu");

/*  Not a pure module */
