// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");

function createElement(f, childrenOpt, param) {
  var children = childrenOpt !== undefined ? childrenOpt : /* [] */0;
  console.log(children);
  var reducer = function (state, item) {
    return state + Curry._1(f, item) | 0;
  };
  return List.fold_left(reducer, 0, children);
}

function make(f, children) {
  console.log(children);
  var reducer = function (state, item) {
    return state + Curry._1(f, item) | 0;
  };
  return $$Array.fold_left(reducer, 0, children);
}

exports.createElement = createElement;
exports.make = make;
/* No side effect */
