// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var box = {
  contents: 99
};

var box2 = {
  contents: 99
};

box.contents = 100;

box2.contents = 100;

Pervasives.print_int(box.contents);

Pervasives.print_int(box.contents);

exports.box = box;
exports.box2 = box2;
/*  Not a pure module */
