// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var shared = [
  "name",
  "age"
];

console.log("Mr.X");

var $$class = CamlinternalOO.create_table(shared);

var ids = CamlinternalOO.get_method_labels($$class, shared);

var name = ids[0];

var age = ids[1];

CamlinternalOO.set_methods($$class, [
      name,
      (function (self$1) {
          return "Mr.y";
        }),
      age,
      (function (self$1) {
          return 22;
        })
    ]);

CamlinternalOO.init_class($$class);

var obj1 = CamlinternalOO.create_object_opt(undefined, $$class);

console.log(Caml_oo_curry.js1(-922783157, 1, obj1));

var vanillaJsObj1 = {
  name: "Mr.Record",
  age: 22
};

console.log(vanillaJsObj1.name);

function recTestTypeToJs(param) {
  return {
          name: param.name,
          age: param.age
        };
}

function recTestTypeFromJs(param) {
  return {
          name: param.name,
          age: param.age
        };
}

var testRec1 = recTestTypeFromJs(vanillaJsObj1);

console.log(testRec1.name);

var testRec2 = {
  name: "Mrs.Record",
  age: 99
};

var testJs2 = recTestTypeToJs(testRec2);

console.log(testJs2.name);

var rec1 = {
  name: "Mr.X",
  age: 22
};

exports.rec1 = rec1;
exports.obj1 = obj1;
exports.vanillaJsObj1 = vanillaJsObj1;
exports.recTestTypeToJs = recTestTypeToJs;
exports.recTestTypeFromJs = recTestTypeFromJs;
exports.testRec1 = testRec1;
exports.testRec2 = testRec2;
exports.testJs2 = testJs2;
/*  Not a pure module */
