// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function test1(a) {
  console.log("test1: " + a);
  
}

test1(22);

function test2(a, b) {
  console.log("test2: " + a + ", " + b);
  
}

test2(1, 2);

function fMitX(param) {
  var x = "Was ist das?";
  console.log("x: " + x + ", y: " + param);
  
}

fMitX(0);

function test3(a, b, c) {
  console.log("test3: " + a + ", " + b + ", " + c);
  
}

test3(1, 2, 3);

test3(1, 2, 3);

test3(1, 2, 3);

function f(x, y) {
  if (x !== undefined) {
    console.log("x: " + Caml_option.valFromOption(x) + ", y: " + y);
  } else {
    console.log("x: None, y: " + y);
  }
  
}

f(undefined, "\xc3\x9cberraschung");

function f$1(x, y, param) {
  if (x !== undefined) {
    console.log("x: " + Caml_option.valFromOption(x) + ", y: " + y);
  } else {
    console.log("x: None, y: " + y);
  }
  
}

function g(param) {
  return function (param$1) {
    return f$1(param, "Schon wieder Curry auf Aufruf.", param$1);
  };
}

g(undefined)(undefined);

f$1(undefined, "Yooo. Heute mal kein scharfes Curry auf den Aufruf.", undefined);

function optionalToString(optional) {
  if (optional !== undefined) {
    return "Some: " + optional;
  } else {
    return "None";
  }
}

function f$2(optional1, optional2, mandatory) {
  var optional1$1 = optionalToString(optional1);
  var optional2$1 = optionalToString(optional2);
  console.log("optional1: " + optional1$1 + ", optional2: " + optional2$1 + ", mandatory: " + mandatory);
  
}

f$2(undefined, undefined, "hallo");

function times(n, f) {
  var _acc = n;
  while(true) {
    var acc = _acc;
    if (acc <= 0) {
      return ;
    }
    Curry._1(f, undefined);
    _acc = acc - 1 | 0;
    continue ;
  };
}

function test6(spruchOpt, repCount) {
  var spruch = spruchOpt !== undefined ? spruchOpt : "Oben ist oben";
  return times(repCount, (function (param) {
                console.log(spruch);
                
              }));
}

test6(undefined, 10);

test6("Atmen ist gesund", 2);

function feller_specialAttack(param) {
  return "kratzen";
}

var feller = {
  name: "Max",
  alter: 3,
  specialAttack: feller_specialAttack
};

function pfoter_specialAttack(param) {
  return "miauen";
}

var pfoter = {
  name: "Moritz",
  alter: 2,
  specialAttack: pfoter_specialAttack
};

function mapToFeller(feller, pfoter) {
  return feller.name;
}

console.log("Max");

console.log("elf");

function f$3(x) {
  var value = x + 1 | 0;
  console.log(" x + 1 : " + value);
  
}

f$3(11);

exports.test1 = test1;
exports.test2 = test2;
exports.fMitX = fMitX;
exports.test3 = test3;
exports.g = g;
exports.optionalToString = optionalToString;
exports.times = times;
exports.test6 = test6;
exports.feller = feller;
exports.pfoter = pfoter;
exports.mapToFeller = mapToFeller;
exports.f = f$3;
/*  Not a pure module */
