// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var mrMax = [
  22,
  "Max Musterman",
  1.77
];

function logDenMal(pData) {
  console.log("" + pData[1] + " ist " + pData[0] + " alt und ist " + pData[2] + " m gross.");
  
}

logDenMal(mrMax);

function schliesse(ding) {
  return {
          TAG: /* Geschlossen */0,
          _0: ding
        };
}

function oeffne(ding) {
  return {
          TAG: /* Offen */1,
          _0: ding
        };
}

function offenesHolzhuettenFenster(f) {
  return {
          TAG: /* Offen */1,
          _0: f
        };
}

function geschlossenesVerandaFenster(f) {
  return {
          TAG: /* Geschlossen */0,
          _0: f
        };
}

var verandaTuer = /* Glas */0;

var holzhuettenFenster = /* Luft */{
  _0: {
    hd: "Pollen",
    tl: {
      hd: "Insekten",
      tl: {
        hd: "K\xc3\xa4lte",
        tl: /* [] */0
      }
    }
  }
};

var container = {
  hd: "weiss",
  tl: {
    hd: "nix",
    tl: {
      hd: "\xc3\xbcber",
      tl: {
        hd: "string",
        tl: {
          hd: "theorie",
          tl: /* [] */0
        }
      }
    }
  }
};

var payloadResults = {
  hd: {
    TAG: /* Ok */0,
    _0: {
      data: "hi"
    }
  },
  tl: {
    hd: {
      TAG: /* Ok */0,
      _0: {
        data: "bye"
      }
    },
    tl: {
      hd: {
        TAG: /* Error */1,
        _0: "Something wrong happened!"
      },
      tl: /* [] */0
    }
  }
};

exports.verandaTuer = verandaTuer;
exports.holzhuettenFenster = holzhuettenFenster;
exports.mrMax = mrMax;
exports.logDenMal = logDenMal;
exports.schliesse = schliesse;
exports.oeffne = oeffne;
exports.offenesHolzhuettenFenster = offenesHolzhuettenFenster;
exports.geschlossenesVerandaFenster = geschlossenesVerandaFenster;
exports.container = container;
exports.payloadResults = payloadResults;
/*  Not a pure module */
