// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var dict1 = {};

var obj1 = {
  art: "test",
  gueltig: true,
  id: 284
};

dict1["y"] = obj1;

console.log(dict1);

var obj2 = {
  art: "test",
  gueltig: true,
  id: 284
};

var dict2 = {};

dict2["x"] = obj2;

console.log(dict2);

var x = Object.assign({}, dict1, dict2);

console.log(x);

const val = { secret: "ley" };
;

console.log(val.secret);

const jsObject = {
      myName: "blabla",
      myMethod: (greeting) => console.log(`${greeting}, Mr.${jsObject.myName}`)
    };
;

console.log(jsObject.myName);

jsObject.myName = "HERBERT";

console.log(jsObject.myName);

var hello = jsObject.myMethod("Hello");

exports.dict1 = dict1;
exports.obj1 = obj1;
exports.obj2 = obj2;
exports.dict2 = dict2;
exports.x = x;
exports.hello = hello;
/*  Not a pure module */
